# name of the file
name: tests-expiration

# when you want to run this workflow

on:
# when a pull request is created or updated and the path is tickets/** (any file in the orders folder)
  pull_request:
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && npm install && npm run test:ci
